
# spring application config
spring:
  profiles:
    active: dev
  datasource:
    # druid connection pool
    druid:
      initial-size: 10
      min-idle: 30
      max-active: 100
      max-wait: 3000
      remove-abandoned-timeout: 180

# myBatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
