
# myBatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml

spring:
  # db
  datasource:
    url: your db connect url    ?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username:
    password:
    # druid connect pool
    druid:
      initial-size: 10
      min-idle: 30
      max-active: 100
      max-wait: 3000
      remove-abandoned-timeout: 180
