spring:
  # db
  datasource:
    url: jdbc:mysql://10.144.251.194:3306/lcn-payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: github:lcn29
