spring:
  # db
  datasource:
    url: jdbc:mysql://10.144.6.213:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: github:lcn29
    # druid connect pool
    druid:
      initial-size: 10
      min-idle: 30
      max-active: 100
      max-wait: 3000
      remove-abandoned-timeout: 180

# alipay sand box config
alipay:
  application:
    app-id: 2016102000728126
    tenant-id: 2088102180441393
    open-api-domain: https://openapi.alipay.com/gateway.do
    mcloud-api-domain: http://mcloudmonitor.com/gateway.do
    sign-type: RSA2
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqCcvjIgkbPwuDEQakEC5KB3EDTXWrbh4dvwg6qKGUsEuXInXKlgISDvmCKkowWrTRFA6VpFiTAyiL5UY2jULzo+t6JXFB9mnCUqkMOvkcWWmh0gxhObQdGmzMN7JRBwg9tBlGH+8MwmVdee6HJHb95eSrSBmlvPAwXI+bn5hovjNjYRXR5parZtJkmThYReqmWTb2jG2ZrhGSR4H+8tWSmEGIN+BQ+ruMh0kIVbZfXYMqiEqzSXihwUcyJxgAd7EeJzSlQQYJ0wFzi9DbAMlEAHhTaRuPykDnPF4zSFNDpJU99RqglGjjUGyVmSbgHyFeTiWZWvmFeU7AQHkkPtYOQIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCoJy+MiCRs/C4MRBqQQLkoHcQNNdatuHh2/CDqooZSwS5cidcqWAhIO+YIqSjBatNEUDpWkWJMDKIvlRjaNQvOj63olcUH2acJSqQw6+RxZaaHSDGE5tB0abMw3slEHCD20GUYf7wzCZV157ockdv3l5KtIGaW88DBcj5ufmGi+M2NhFdHmlqtm0mSZOFhF6qZZNvaMbZmuEZJHgf7y1ZKYQYg34FD6u4yHSQhVtl9dgyqISrNJeKHBRzInGAB3sR4nNKVBBgnTAXOL0NsAyUQAeFNpG4/KQOc8XjNIU0OklT31GqCUaONQbJWZJuAfIV5OJZla+YV5TsBAeSQ+1g5AgMBAAECggEAGJxjoTXr3uep9bGiEarnbq+smiJfIV32g7OzPaQ79LDBkFm8XD42OBxMNshLZsOz2DPF1hXBRVA0DLLNyGIrMDhnQ7tn8xYwFHQQQ/jCnrY6AWLXnJQLvn4Z8/UnkAht6rHlmghYC0BD19Xqr3PJthtBJIWxfjZ+59FIwfNNZwS1iOo5hilAO5PCMm4jXR4oYLJQrr/cdc3IsBbFAXGcduU4ZEcSwnYNl7+ChuXYbLEO0lB4dfPXcbsauO33QptQOlem7s406VbkNwTwbLGjyCd31hXI9pQ94auO7ZlU4c4X3ExVANUJQGiWkEkqYJTjrMPnyTUDqzacux15K3QeYQKBgQD5xJBMgPQNWpVVb4PQAuVzt5rTyyX7RtUKfojme0HD4pLbnfxhYGBP226cTZJHmr8MdzyGL8jwoH3Sc4Ib42QoI6zxOpTl/SxmnGAOSDSGTMnIIpejsLt+ja04YfpQhnwv5bByYuGHSQUjs7r1aKAvfDuqkCfkyixR9uIahUfVLwKBgQCsWUsW75HZC5qd7RC9XwJ0Z2AX1Id7WNXSlklpcx+DO5BETmCx47u5g2IIZ0tQRRqd5MRUKb0YLw3lqTUp14ZHNA87fwVonz1dfSXochxTWGBzwyIq8mz5Q/coeXNbddvP0OhdZx+PoX3rRqWFYR1X3Zzu5jfrFaSg0562zhGfFwKBgDWdUCxb8gd7zlqMmYrpVD/GxeF41ipeRhT+nHx9MNzPoh6qhyaP/ZymydObgy8DtMcEQWW8lDGzAc9PJDrAURucrN8LaDMGaaWNI8FtFnlNunLPmiV1Joo/91MHFSh79eSCNaIYP7k+n2/OgO91Cg2naVdvomCmVWUyzc5LlePZAoGBAKAxoxTfeo3mNkHCHsQV8l8l0vBzb7ZbnOtPG08zXUAKdg63VzMhfNRy5QTwldU3VgUapM2hugwneGBWRX7tv/ag0eO4LdvP3ybtcvW6Us+5HnWbE0Ad8uJBpRJuyKVjR/vCrqhaeMB1F2g/UwxFdxO7femj/Ke6hzmhWS2LHl/jAoGALvRklY7FwGskPJmNJ4YrRuuzkbIp03wKr/enWc6e22GOFZWmcGt0eWe23UFU1iZQ7iCFLamtS+EA9eKoZJ2RiorN71z4XCnWX1C5JeJHNmhwmoZdZZWg29euLZXW4rlZgUft3isre2HcQ95MaShAS2od4XBiA2tN7yPwFNWeyWo=
  platform:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk14GvWyfk+gtoIfIEpbgTDzjRFH3gDMzNWuA0Xuv9eMV+W+A0avSnaRJQ1lm4Zb6ER6/h+sGMW7g38X0n58Y2yH9egqSkbLH6RBpIUa2crE6RGlBbuZZJ3K8yMSaNOYbjm3iZhswQpQL+Q6Bn9/mUrdSkCIFqEXsj3Z+IUz9UjVIx1uihzISXbURuBYw6AjwbfiKexFKQTDmfWZjkZemNitTWd2a6c1Re3Yai6r1ET331PdU0pYA4qAtW7eo+hkSvRHY8EX99Ytpoc1HTN5a2dUzW42yNIJyKtAXYjgqAZ9/e4QSFQQuxxAGg95IEpm2bTj9pjo9x3OxhCrWb8J5jwIDAQAB
  pay-by-face-to-face:
    # maximum number of query and query interval (ms)
    max-query-try: 5
    query-duration: 5000
    # maximum number of revocation and revocation interval (ms)
    max-cancel-retry: 3
    cancel-duration: 3000
    # transaction safeguard thread first scheduling delay and scheduling interval (seconds)
    heartbeat-delay: 5
    heartbeat-duration: 900


